services:
  # Django Backend with ASGI support for WebSockets
  - type: web
    name: vikrahub-backend
    runtime: python3
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: cd backend && daphne vikrahub.asgi:application --bind 0.0.0.0 --port $PORT
    plan: free
    env: python
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: REDIS_URL
        # Set this to the connection string of your Redis instance provisioned on Render
        # Example: redis://red-xxxxxxxxxxxx:6379
        fromSecret:
          name: REDIS_URL 
      - key: ALLOWED_HOSTS
        value: api.vikrahub.com,vikrahub.com,.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://vikrahub.com,https://www.vikrahub.com,https://vikrahub-frontend.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        value: dxpwtdjzp
      - key: CLOUDINARY_API_KEY
        value: 415637895317185
      - key: CLOUDINARY_API_SECRET
        fromSecret:
          name: CLOUDINARY_API_SECRET

  # React Frontend with proper API configuration
  - type: static
    name: vikrahub-frontend
    buildCommand: |
      cd frontend
      npm ci
      echo "Building with REACT_APP_API_URL=${REACT_APP_API_URL}"
      echo "Building with REACT_APP_WS_URL=${REACT_APP_WS_URL}"
      npm run build
      echo "Frontend build completed for static hosting - Build $(date)"
    staticPublishPath: frontend/build
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://api.vikrahub.com/api/
      - key: REACT_APP_WS_URL
        value: wss://api.vikrahub.com/ws/
      - key: REACT_APP_CLOUDINARY_CLOUD_NAME
        value: dxpwtdjzp
      - key: REACT_APP_CLOUDINARY_API_KEY
        value: 415637895317185

# PostgreSQL Database
databases:
  - name: vikrahub-db
    plan: free
