# Generated by Django 5.2.4 on 2025-07-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_slug_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True, help_text="List or describe the benefits for the 'Benefits' tab"),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='overview',
            field=models.TextField(blank=True, help_text="Main overview content for the 'Overview' tab"),
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.TextField(blank=True, help_text="Explain the process for the 'Process' tab"),
        ),
    ]
