# Generated by Django 5.2.4 on 2025-08-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_enhanced_messaging_features'),
        ('messaging', '0002_message_recipient'),
    ]

    operations = [
    ]
