# Generated by Django 5.2.4 on 2025-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assetcategory_projectcategory_creativeasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('seller', 'Seller')], default='client', max_length=20),
        ),
    ]
