# Generated by Django 5.2.4 on 2025-07-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_portfolioitem_tags_portfolioitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, help_text='Cloudinary URL for blog post image', null=True),
        ),
        migrations.AlterField(
            model_name='creativeasset',
            name='asset_files',
            field=models.URLField(help_text='Cloudinary URL for the asset files (ZIP)'),
        ),
        migrations.AlterField(
            model_name='creativeasset',
            name='preview_image',
            field=models.URLField(help_text='Cloudinary URL for asset preview image'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.URLField(blank=True, help_text='Cloudinary URL for portfolio image', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, help_text='Cloudinary URL for service image', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.URLField(blank=True, help_text='Cloudinary URL for team member image', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='Cloudinary URL for avatar image', null=True),
        ),
    ]
