# Generated by Django 5.2.4 on 2025-07-17 15:44

import core.cloudinary_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_convert_images_to_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeasset',
            name='asset_files',
            field=models.FileField(help_text='Asset files (ZIP or individual files)', upload_to='assets/files/'),
        ),
        migrations.AlterField(
            model_name='creativeasset',
            name='preview_image',
            field=models.ImageField(help_text='Preview image for the asset', upload_to='assets/previews/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='Cloudinary URL for avatar image', null=True, validators=[core.cloudinary_utils.validate_cloudinary_url]),
        ),
    ]
