# Generated by Django 5.2.4 on 2025-07-19 12:13

import core.cloudinary_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_creativeasset_asset_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeasset',
            name='asset_files',
            field=models.URLField(blank=True, help_text='Cloudinary URL for asset files (ZIP or individual files)', null=True, validators=[core.cloudinary_utils.validate_cloudinary_url]),
        ),
        migrations.AlterField(
            model_name='creativeasset',
            name='preview_image',
            field=models.URLField(blank=True, help_text='Cloudinary URL for preview image', null=True, validators=[core.cloudinary_utils.validate_cloudinary_url]),
        ),
    ]
