# Generated by Django 5.2.4 on 2025-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_creativeasset_asset_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('creator', 'Creator')], default='client', max_length=20),
        ),
    ]
