# Generated by Django 5.2.4 on 2025-07-22 16:05

from django.db import migrations


def update_seller_to_creator(apps, schema_editor):
    """Update all user_type='seller' to user_type='creator'"""
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(user_type='seller').update(user_type='creator')


def reverse_creator_to_seller(apps, schema_editor):
    """Reverse migration: update creator back to seller"""
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(user_type='creator').update(user_type='seller')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_seller_to_creator'),
    ]

    operations = [
        migrations.RunPython(update_seller_to_creator, reverse_creator_to_seller),
    ]
