# Generated by Django 5.2.4 on 2025-07-23 09:19

import core.cloudinary_utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_migrate_seller_data_to_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business/Company'), ('nonprofit', 'Non-Profit Organization'), ('government', 'Government Agency'), ('media', 'Media Organization'), ('agency', 'Creative Agency'), ('startup', 'Startup'), ('other', 'Other')], default='individual', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='Organization or company name', max_length=200)),
                ('company_size', models.CharField(choices=[('solo', 'Solo/Individual'), ('small', 'Small (2-10 employees)'), ('medium', 'Medium (11-50 employees)'), ('large', 'Large (51-200 employees)'), ('enterprise', 'Enterprise (200+ employees)')], default='solo', max_length=20)),
                ('industry', models.CharField(blank=True, help_text='Industry or sector', max_length=100)),
                ('business_address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('typical_budget_range', models.CharField(blank=True, help_text='Typical project budget range', max_length=100)),
                ('project_types', models.TextField(blank=True, help_text='Types of projects typically commissioned')),
                ('preferred_communication', models.CharField(blank=True, help_text='Preferred communication methods', max_length=100)),
                ('business_registration', models.CharField(blank=True, help_text='Business registration number', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('projects_posted', models.PositiveIntegerField(default=0)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('payment_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_type', models.CharField(choices=[('artist', 'Visual Artist'), ('photographer', 'Photographer'), ('designer', 'Graphic Designer'), ('writer', 'Writer/Storyteller'), ('musician', 'Musician'), ('filmmaker', 'Filmmaker'), ('digital_artist', 'Digital Artist'), ('traditional_artist', 'Traditional Artist'), ('other', 'Other Creative')], help_text='Primary creative field', max_length=50)),
                ('artistic_style', models.CharField(blank=True, help_text='Description of artistic style or approach', max_length=200)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-2 years)'), ('intermediate', 'Intermediate (3-5 years)'), ('advanced', 'Advanced (6-10 years)'), ('expert', 'Expert (10+ years)')], default='beginner', max_length=20)),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to external portfolio')),
                ('featured_work', models.URLField(blank=True, help_text='Cloudinary URL for featured artwork', validators=[core.cloudinary_utils.validate_cloudinary_url])),
                ('art_statement', models.TextField(blank=True, help_text='Artist statement or creative philosophy')),
                ('years_active', models.PositiveIntegerField(default=0, help_text='Years active as a creator')),
                ('exhibitions', models.TextField(blank=True, help_text='Notable exhibitions, shows, or features')),
                ('awards', models.TextField(blank=True, help_text='Awards and recognitions')),
                ('available_for_commissions', models.BooleanField(default=True)),
                ('commission_types', models.CharField(blank=True, help_text='Types of commissions accepted', max_length=300)),
                ('price_range', models.CharField(blank=True, help_text='Typical price range for work', max_length=100)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Profile',
                'verbose_name_plural': 'Creator Profiles',
            },
        ),
    ]
