# Generated by Django 5.2.4 on 2025-07-23 12:37

import core.cloudinary_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clientprofile_creatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.TextField(blank=True, help_text='Awards, recognitions, and notable achievements'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.URLField(blank=True, help_text='Cloudinary URL for cover photo', null=True, validators=[core.cloudinary_utils.validate_cloudinary_url]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country or general location', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='services_offered',
            field=models.TextField(blank=True, help_text='Services and commissions offered'),
        ),
    ]
