# Generated by Django 5.2.4 on 2025-07-27 07:47

import core.cloudinary_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_author_to_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeasset',
            name='currency',
            field=models.CharField(choices=[('SSP', 'South Sudanese Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='SSP', max_length=3),
        ),
        migrations.AlterField(
            model_name='creativeasset',
            name='asset_files',
            field=models.URLField(blank=True, help_text='Cloudinary URL for asset files (ZIP or individual files) - Optional', null=True, validators=[core.cloudinary_utils.validate_cloudinary_url]),
        ),
        migrations.AlterField(
            model_name='creativeasset',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for free assets', max_digits=10, null=True),
        ),
    ]
