# Generated by Django 5.2.4 on 2025-08-06 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_create_enhanced_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='device',
            name='core_device_user_token_unique',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='core_device_user_id_d6df6b_idx',
            old_name='core_device_user_id_active_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='core_device_platfor_b7d501_idx',
            old_name='core_device_platform_active_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_1cc5b6_idx',
            old_name='core_notification_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_cb8f07_idx',
            old_name='core_notification_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_verb_15282c_idx',
            old_name='core_notification_verb_created_idx',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'token')},
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['token'], name='core_emailv_token_606d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', '-created_at'], name='core_emailv_user_id_7dd422_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'is_verified'], name='core_emailv_email_5fec77_idx'),
        ),
    ]
