# Generated by Django 5.2.4 on 2025-08-07 16:28

from django.db import migrations


def update_site_domain(apps, schema_editor):
    """Update Django Site domain to vikrahub.com"""
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(pk=1)  # Default site has pk=1
        site.domain = 'vikrahub.com'
        site.name = 'VikraHub'
        site.save()
        print(f"✅ Updated site domain to: {site.domain}")
    except Site.DoesNotExist:
        # Create the site if it doesn't exist
        Site.objects.create(
            pk=1,
            domain='vikrahub.com',
            name='VikraHub'
        )
        print("✅ Created new site with domain: vikrahub.com")


def reverse_update_site_domain(apps, schema_editor):
    """Reverse migration - reset to example.com"""
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(pk=1)
        site.domain = 'example.com'
        site.name = 'example.com'
        site.save()
    except Site.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_emailverification_and_more'),
        ('sites', '0002_alter_domain_unique'),  # Ensure sites app migration dependency
    ]

    operations = [
        migrations.RunPython(
            update_site_domain,
            reverse_update_site_domain,
        ),
    ]
