# Generated by Django 5.2.4 on 2025-08-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_add_username_index"),
    ]

    operations = []
